services:
  app:
    container_name: portainer
    image: docker.io/portainer/portainer-ce:latest
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: "https://loki.hughboi.cc/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    volumes:
      - /run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.hughboi.cc`)"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer.middlewares=portainer-https-redirect"
      - "traefik.http.routers.portainer-secure.entrypoints=https"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.hughboi.cc`)"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    networks:
      - proxy 


volumes:
  portainer-data:
    driver: local


networks:
  proxy:
    external: true
